-- Migration: 019_add_saved_reports.sql
-- Description: Add saved_reports table for storing generated trip reports
-- Created: 2025-01-XX

-- =============================================
-- CREATE SAVED_REPORTS TABLE
-- =============================================

CREATE TABLE IF NOT EXISTS public.saved_reports (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    report_type text NOT NULL DEFAULT 'trip_report',
    generated_by_user_id uuid NOT NULL,
    driver_user_id uuid,
    driver_profile_id uuid,
    driver_name text,
    driver_phone text,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    report_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    summary_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT saved_reports_pkey PRIMARY KEY (id),
    CONSTRAINT fk_saved_reports_generated_by FOREIGN KEY (generated_by_user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_reports_driver_user FOREIGN KEY (driver_user_id) REFERENCES public.users(id) ON DELETE SET NULL,
    CONSTRAINT fk_saved_reports_driver_profile FOREIGN KEY (driver_profile_id) REFERENCES public.driver_profiles(id) ON DELETE SET NULL
);

-- Add index for faster queries
CREATE INDEX IF NOT EXISTS idx_saved_reports_generated_by ON public.saved_reports(generated_by_user_id);
CREATE INDEX IF NOT EXISTS idx_saved_reports_created_at ON public.saved_reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_saved_reports_driver ON public.saved_reports(driver_user_id);

-- Add comment
COMMENT ON TABLE public.saved_reports IS 'Stores saved trip reports generated by customer support and admins';
COMMENT ON COLUMN public.saved_reports.report_data IS 'JSONB object containing the full trip data for the report';
COMMENT ON COLUMN public.saved_reports.summary_data IS 'JSONB object containing summary statistics (total trips, total fare, etc.)';

